spring.application.name=product-service
server.servlet.context-path=/product-service

# Postgres DB Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:static/data.sql
spring.sql.init.continue-on-error=true

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/docs