spring.application.name=product-service
server.servlet.context-path=/product-service

# Postgres DB Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.defer-datasource-initialization=true