spring.application.name=${APPLICATION_NAME}
server.servlet.context-path=${SERVLET_CONTEXT_PATH}

# Database Properties
spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}
spring.jpa.defer-datasource-initialization=${DATA_SOURCE_INIT}
spring.jpa.hibernate.ddl-auto=${DATA_SOURCE_DDL_AUTO}

spring.sql.init.mode=${SQL_INIT_MODE}
spring.sql.init.data-locations=${SQL_INIT_DATA_LOCATION}
spring.sql.init.continue-on-error=${SQL_INIT_ERROR}

logging.level.org.hibernate.SQL=${SQL_LOGGING_LEVEL}
spring.jpa.properties.hibernate.format_sql=${SQL_LOGGING_FORMAT_SQL}

# Swagger
springdoc.swagger-ui.path=${CUSTOM_SWAGGER_PATH}

# Jwt
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiry.time=${JWT_EXPIRY_TIME}